In [1]:
import pandas as pd
df = pd.read_csv("./test/sample_input.csv",sep="\t")
df

         Name                                    REACTION-SMILES
0       90210  N=c1[nH]c2c(c(=O)[nH]1)NC(CN(C=O)c1ccc(C(=O)N[...
1       74648  C=C1C(=O)O[C@@H]2/C=C(\C)CC/C=C(\C)CC[C@@H]12....
2       42601  CN1[C@@H]2C[C@H](OC(=O)[C@H](CO)c3ccccc3)C[C@H...
3  Islatravir  OC[C@@](O)(C=O)C#C.CC(=O)OP(O)(O)=O>>O[C@](COP...
4          A2  [O-][N+](=O)C1=CC(=CC=C1)[C@@H]1CO1>>NC1=CC(=C...
5          A3  OC=O.NC1=CC(=CC=C1)[C@@H]1CO1>>O=CNC1=CC(=CC=C...

In [2]:
%run enzFinder.py -h

usage: enzFinder.py [-h] --mapped MAPPED --i I

Predict EC number for a chemical reaction

options:
  -h, --help       show this help message and exit
  --mapped MAPPED  If reaction is atom-atom mapped - 1, If reaction is not
                   atom-atom mapped - 0, Default-1
  --i I            Enter input file path with header. File should have be in
                   following format. column A - Reaction ID, column B - Atom-
                   atom mapped or unmapped SMARTS of a reaction

In [3]:
%run enzFinder.py --mapped 0 --i ./test/sample_input.csv

Loading data. ...
EnzFinder has started predicting enzyme for given query reaction(s).
started with reaction name : 90210
90210 : RDM generated.
90210 : Round-1 completed.
Successful : Prioritizing EC level-3 and level-4 for 90210 is completed.
Result EC level-3 and level-4 for 90210 is saved in ./result/90210 folder.
started with reaction name : 74648
74648 : RDM generated.
74648 : Round-1 completed.
Successful : Prioritizing EC level-3 and level-4 for 74648 is completed.
Result EC level-3 and level-4 for 74648 is saved in ./result/74648 folder.
started with reaction name : 42601
42601 : RDM generated.
42601 : Round-1 completed.
Successful : Prioritizing EC level-3 and level-4 for 42601 is completed.
Result EC level-3 and level-4 for 42601 is saved in ./result/42601 folder.
started with reaction name : Islatravir
Islatravir : RDM generated.
Islatravir : Round-1 completed.
Successful : Prioritizing EC level-3 and level-4 for Islatravir is completed.
Result EC level-3 and level-4 for Islatravir is saved in ./result/Islatravir folder.
started with reaction name : A2
A2 : RDM generated.
A2 : Round-1 completed.
Successful : Prioritizing EC level-3 and level-4 for A2 is completed.
Result EC level-3 and level-4 for A2 is saved in ./result/A2 folder.
started with reaction name : A3
A3 : RDM generated.
A3 : Round-1 completed.
Successful : Prioritizing EC level-3 and level-4 for A3 is completed.
Result EC level-3 and level-4 for A3 is saved in ./result/A3 folder.
All results are saved in ./result/{query reaction name} folder

In [4]:
!ls ./result/90210

90210_predicted_EC_level3.csv  90210_predicted_EC_level4.csv

In [5]:
# result for EC level 3
df = pd.read_csv("./result/90210/90210_predicted_EC_level3.csv", sep="\t")
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

,Reaction-Name,MetaCyc-Reaction-ID,Predicted-EC-number,Initial-Screening-Weighted-Score,Final-Score
0,90210,FORMYLTHFDEFORMYL-RXN,3.5.1,0.363,1.000
1,90210,FORMYLTETRAHYDROFOLATE-DEHYDROGENASE-RXN,1.5.1,0.617,1.000
2,90210,"FORMATE--DIHYDROFOLATE-LIGASE-RXN,FORMATETHFLI...",6.3.4,0.167,1.000
3,90210,RXN-19393,1.14.13,0.240,0.575
4,90210,FORMYLMETHANOFURAN-DEHYDROGENASE-RXN,1.2.7,0.183,0.319
5,90210,"KETAMID-RXN||R218-RXN,1.3.1.20-RXN,RXN-22011,R...",1.3.1,0.221,0.000
6,90210,"RXN-4261,RXN-4261||AMINOPROPDEHYDROG-RXN,RXN-1...",1.1.1,0.413,0.000
7,90210,"RXN-12655,RXN-12537,RXN-6543,RXN-14317,RXN-143...",1.14.11,0.144,0.000
8,90210,"RXN-18853,ERYTH4PDEHYDROG-RXN,1.2.1.25-RXN,RXN...",1.2.1,0.177,0.000
9,90210,"RXN-22038,RXN-23203,RXN-22588,RXN0-1862,RXN-22...",2.1.2,0.333,0.000

In [6]:
# result for EC level 4
df = pd.read_csv("./result/90210/90210_predicted_EC_level4.csv", sep="\t",na_filter=False)
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df[df['Rank'] == 1]

,Reaction-Name,MetaCyc-Reaction-ID,Predicted-EC-number,Final-Score,Rank
0,90210,FORMYLTHFDEFORMYL-RXN,3.5.1.10,0.818,1
1,90210,FORMYLTETRAHYDROFOLATE-DEHYDROGENASE-RXN,1.5.1.6,0.818,1
2,90210,FORMATETHFLIG-RXN,6.3.4.3,0.818,1